### ISSUE TITLE
Update ipympl

### ISSUE THREAD

**Issue by mpmdean** [NSLS-II-SIX/sixtools#12]

**Comment by mpmdean** [comment]
The conda mirror used by NSLS-II has a very out of date version of ipympl. We should wait for this to be installed and then update.

**Comment by licode** [comment]
install with -c conda-forge. 0.2.1 is ready.

**Comment by mpmdean** [comment]
Thanks @licode 

The required command is
`conda install -c conda-forge ipympl
`

after having done
`conda activate [your_environment]`

**Comment by mpmdean** [comment]
Adding a note that the cloned environment e.g. SIX.2018.3.2 sometimes have pip and conda versions of the same package that can cause issues.
