### ISSUE TITLE
Sphinx webpages

### ISSUE THREAD

**Issue by mpmdean** [NSLS-II-SIX/sixtools#25]
I can successfully build the html locally, but it's not clear to me if they are being pushed somewhere where they can be read.

The link in the readme https://awalter-bnl.github.io/sixtools doesn't seem to work.

**Comment by danielballan** [comment]
The link is wrong but the docs are up at: https://nsls-ii-six.github.io/sixtools/

**Comment by mpmdean** [comment]
Thanks. I was even able to guess the link to scikit-beam/rixs too!
