### ISSUE TITLE
Directions conventions

### ISSUE THREAD

**Issue by mpmdean** [NSLS-II-SIX/sixtools#39]
@ambarb @bisogni discussed with @mpmdean .

images should be plotted as if the user is looking upstream and with the top of the image corresponding to the top of the CCD.

The axes definition is:
Positive x is left to right
Positive y is low to high, such that positive y is energy loss.

Modify image_to_photon_events

**Comment by mpmdean** [comment]
This is corrected, so I will close.

**Comment by mpmdean** [comment]
On the controls screen now. The image is displayed inverted w.r.t. real space. In this display, the top of the image is low pixel numbers.

**Comment by bisogni** [comment]
The display of the CCD image on the screen is now fixed. I will close this comment.
